#!/bin/bash

. ./common

known=('health' 'state' 'stats')

if [ $# -lt 1 ]; then
    $CURL $ES_URL/_cluster/health?pretty
elif [[ " ${known[*]} " == *" $1 "* ]]; then
    $CURL $ES_URL/_cluster/$1?pretty
else
    echo "Unknown cluster info category: $1"
    echo "Accepted info categories: ${known[@]}"
fi
