#!/bin/bash

. ./setenv


regular=0
synonym=0


function total()
{
    local search=$1
    local expected=$2
    local output=$(echo "$3" | grep total)

    local CNT=0

    for t in $output; do
        n=${t::-1}
        if [[ $n =~ ^-?[0-9]+$ ]]; then
            CNT=$((n))
        fi
    done

    if (( CNT != expected )); then
        if [[ $search = "regular" ]]; then
            regular=$((regular+1))
            echo "[FAILED]"
        elif [[ $search = "synonym" ]]; then
            synonym=$((synonym+1))
            echo "[FAILED]"
        fi
    fi

    echo $"$3"
    echo
}


# Regular search
echo "==== [Regular] [term:notthere] [0] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":\"notthere\"}}}")
total "regular" 0 "$OUT"

echo "==== [Regular] [term:remove] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":\"remove\"}}}")
total "regular" 1 "$OUT"

echo "==== [Regular] [term:delete] [0] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":\"delete\"}}}")
total "regular" 0 "$OUT"

echo "==== [Regular] [term:found] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":\"found\"}}}")
total "regular" 1 "$OUT"


echo "==== [Regular] [phrase:no such phrase] [0] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match_phrase\":{\"symptom\":\"no such phrase\"}}}")
total "regular" 0 "$OUT"

echo "==== [Regular] [phrase:cannot remove file] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match_phrase\":{\"symptom\":\"cannot remove file\"}}}")
total "regular" 1 "$OUT"

echo "==== [Regular] [phrase:cannot delete file] [0] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match_phrase\":{\"symptom\":\"cannot delete file\"}}}")
total "regular" 0 "$OUT"


# Synonym search
echo "==== [Synonym] [term:notthere] [0] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"notthere\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 0 "$OUT"

echo "==== [Synonym] [term:remove] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"remove\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [term:delete] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"delete\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [term:erase] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"erase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [term:found] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"erase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [term:cannot] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"cannot\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [term:can not] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"can not\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"


echo "==== [Synonym] [phrase:no such phrase] [0] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"no such phrase\",\"type\":\"phrase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 0 "$OUT"

echo "==== [Synonym] [phrase:cannot remove file] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"cannot remove file\",\"type\":\"phrase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [phrase:cannot delete file] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"cannot delete file\",\"type\":\"phrase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [phrase:can not remove file] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"can not remove file\",\"type\":\"phrase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"

echo "==== [Synonym] [phrase:can not delete file] [1] ===="
OUT=$(curl -s $ES_URL/$INDEX/$TYPE/_search?pretty -d "{\"query\":{\"match\":{\"symptom\":{\"query\":\"can not delete file\",\"type\":\"phrase\",\"analyzer\":\"$ANALYZER\"}}}}")
total "synonym" 1 "$OUT"


echo
echo "==== SUMMARY ===="
echo
echo "Regular: $regular failed"
echo "Synonym: $synonym failed"


echo
exit 0
